name: npm-publish

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NPM_TAG: ${{ contains(github.ref_name, 'beta') && 'beta' || 'latest'  }}
      YARN_NPM_AUTH_TOKEN: ${{secrets.npm_token}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable
      - run: yarn test
      - run: yarn build
      - run: yarn workspace @catsjs/core npm publish --access public --tag $NPM_TAG
      - run: yarn workspace @catsjs/create-spec npm publish --access public --tag $NPM_TAG
      - run: yarn workspace @catsjs/html npm publish --access public --tag $NPM_TAG
      - run: yarn workspace @catsjs/http npm publish --access public --tag $NPM_TAG
      - run: yarn workspace @catsjs/json npm publish --access public --tag $NPM_TAG
      - run: yarn workspace @catsjs/report npm publish --access public --tag $NPM_TAG
